server:
  port: 6001

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: #数据库密码
    url: jdbc:mysql://127.0.0.1:3306/hotsearch?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    # 控制台日志配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mappers/*.xml

mail:
  #微博热搜url
  weibo_hotsearch_url: "https://s.weibo.com/top/summary?cate=realtimehot"
  #微博热搜关键字
  weibo_hotsearch_keyword: #你想关注的热搜关键字
  #邮件标题
  mail_subject: "热搜消息提醒"
  #邮件内容标题
  mail_content_head: "现在有如下关于受关注的热搜:</br>"
  #邮箱服务器地址
  mail_senderserver_host: smtp.163.com
  #发送邮件的端口
  mail_senderserver_port: 25
  #是否需要进行身份验证,视调用的邮箱而定，比方说QQ邮箱就需要，否则就会发送失败
  mail_senderserverauth: false
  #传输协议
  mail_sender_protocol: smtp
  #发件人邮箱
  mail_sender_address: #发件人邮箱
  #发件人邮箱别名
  mail_sender_personalName: "小助手"
  #发件人邮箱用户名
  mail_sender_username: #发件人用户名
  #发件人邮箱客户端授权码
  mail_sender_password: #客户端授权码
  #是否开启debug
  mail_mailDebug: false
  #邮件正文类型
  #mail_contentType:
  #收件人邮箱
  mail_receiver_address: #收件人邮箱