server:
  port: 6001

spring:
  application:
    name: hotsearch
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: db_password #数据库密码
    url: jdbc:mysql://ip_address:3306/hotsearch?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    # 连接池的配置信息
    # 初始化大小，最小，最大
    initial-size: 5
    max-active: 20
    min-idle: 5
    # 配置获取连接等待超时的时间
    max-wait: 3000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    time-between-eviction-runs-millis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 'x' FROM DUAL
    test-while-idle: true
    test-on-borrow: true
    test-on-return: false
    filters: stat,wall,log4j2
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    # 控制台日志配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mappers/*.xml

mail:
  #微博热搜url
  weibo_hotsearch_url: "https://s.weibo.com/top/summary?cate=realtimehot"
  #微博热搜关键字
  weibo_hotsearch_keyword: 千玺 #你想关注的热搜关键字
  #邮件标题
  mail_subject: "热搜消息提醒"
  #邮件内容标题
  mail_content_head: "现在有如下关于受关注的热搜:</br>"
  #邮箱服务器地址
  mail_senderserver_host: smtp.163.com
  #发送邮件的端口
  mail_senderserver_port: 25
  #是否需要进行身份验证,视调用的邮箱而定，比方说QQ邮箱就需要，否则就会发送失败
  mail_senderserverauth: false
  #传输协议
  mail_sender_protocol: smtp
  #发件人邮箱
  mail_sender_address: sender_mail #发件人邮箱
  #发件人邮箱别名
  mail_sender_personalName: "小助手"
  #发件人邮箱用户名
  mail_sender_username: sender_mail #发件人用户名
  #发件人邮箱客户端授权码
  mail_sender_password: sender_client_code #客户端授权码
  #是否开启debug
  mail_mailDebug: false
  #邮件正文类型
  #mail_contentType:
  #收件人邮箱
  mail_receiver_address: receiver_mail #收件人邮箱